### ISSUE TITLE
Repo topic needs to be updated

### ISSUE THREAD

**Issue by anmspro** [sammyBrokeTheWeb/freecodedatabase#15]
In the about section, the topic should be "hacktoberfest" instead of "hactoberfest"

<img width="647" alt="image" src="https://user-images.githubusercontent.com/33668152/193757194-de4cc7ed-b442-4b52-9da8-308399689ae6.png">

**Comment by sammyBrokeTheWeb** [comment]
Oh sorry! fixed!
